// Generated by https://quicktype.io

class Pickup {
  Results? results;

  Pickup({
    this.results,
  });
}

class Results {
  String? totalRecordCount;
  List<Record>? records;
  String? result;

  Results({
    this.totalRecordCount,
    this.records,
    this.result,
  });
}

class Record {
  String? code;
  String? address;
  String? contactPhone;

  Record({
    this.code,
    this.address,
    this.contactPhone,
  });
}
